# Generated by Django 2.1.2 on 2018-10-14 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dweetfeed.dweets.models
import dweetfeed.dweets.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=240, validators=[dweetfeed.dweets.validators.validateDweet])),
                ('commented_at', models.DateTimeField(auto_now_add=True)),
                ('commented_user', models.ForeignKey(default=None, on_delete=models.SET(dweetfeed.dweets.models.get_dummy_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dweet_text', models.TextField(max_length=240, validators=[dweetfeed.dweets.validators.validateDweet])),
            ],
        ),
        migrations.CreateModel(
            name='DweetRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dweet_created_at', models.DateTimeField(auto_now_add=True)),
                ('dweet_last_updated', models.DateTimeField(auto_now=True)),
                ('dweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dweets.Dweet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.IntegerField(choices=[('1', 'Like'), ('0', 'Dislike'), ('', '')], default=0)),
                ('reacted_at', models.DateTimeField(auto_now_add=True)),
                ('dweet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='dweets.Dweet')),
                ('reacted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dweet',
            name='dweeted_user',
            field=models.ManyToManyField(related_name='dweets', through='dweets.DweetRelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='dweet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dweets.Dweet'),
        ),
    ]
